services:
  - type: web
    name: copperx-telegram-bot
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: COPPERX_API_BASE_URL
        value: https://api.copperx.io
    autoDeploy: true
